spring.datasource.url=jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql = true

jwt.secret=vTmAu9to5hos3qt1oA0Yqa5JJ6rMAE2dcUMlPiaKZQ0bXo8FzNO

eureka.client.service-url.defaultZone=${EUREKA_HOST:http://localhost:8761/eureka/}


spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:UGOFtDHhkKtNcQEyuvFH}


minio.endpoint=https://api.media.simsim.fit
