spring.application.name=product-service
server.servlet.context-path=/api/product

spring.profiles.active=local

server.port=9030

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.web.client.RestTemplate=WARN
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
logging.level.org.springframework.web.HttpLogging=WARN

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml